### ISSUE TITLE
cannot GET encryption as byte string

### ISSUE THREAD

**Issue by coderboyorion** [0x10001/des#1]
In the README it says that 
key0.encrypt() -> b"\x  (encrypted byte string)

but in code the encrypt function returns an instance of a DesKey object so it is not possible to do encrypt / decrypt because decrypt expects a message of byte format.
instead we pass in an instance of a DesKey object

**Comment by 0x10001** [comment]
So how does your code look like? And which version of Python are you using?
I need more info about your question. :)

**Comment by coderboyorion** [comment]
Hey littlefisher!

python3.7 and my problem was that I was following the documentation / guide you have and:

when I tried to encrypt key object output was `<DesKey object>` which cannot call `decrypt()` on because it gives error `expected a message of byte format`

**Comment by 0x10001** [comment]
@coderboyorion 
The `encrypt()` and `decrypt()` methods should be called from a `DesKey` object. The code should look like below:
```python
key = DesKey(...)
message = b"..." # should be bytes
encrypted = key.encrypt(message, ...)
decrypted = key.decrypt(encrypted, ...) # should equal message
```
Since you did not post your actual code in the comment, I am not sure whether you wrote your code in an expected way...
