### ISSUE TITLE
Padding is added also to 8 bytes block

### ISSUE THREAD

**Issue by SilDS9** [0x10001/des#5]
When using the padding keyword, in case of 8 bytes input data the payload to encrypt is doubled the length unless using only the data provided.
This is an edge case because in every other situation (input data less than 8 bytes or its multiple) the padding works fine and the output is calculated accordingly.

**Comment by 0x10001** [comment]
> When using the padding keyword, in case of 8 bytes input data the payload to encrypt is doubled the length unless using only the data provided. This is an edge case because in every other situation (input data less than 8 bytes or its multiple) the padding works fine and the output is calculated accordingly.

This padding schema does require extra 8 bytes for encryption. Otherwise, there will be a problem to trail out the padding part at the end of the data from the ciphertext.
